name: Morning Greeting

on:
  schedule:
    # Runs at 9am Dubai time (UTC+4) every day
    - cron: '0 5 * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  create-morning-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create morning greeting issue
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toLocaleDateString('en-US', {
              timeZone: 'Asia/Dubai',
              weekday: 'long',
              year: 'numeric',
              month: 'long',
              day: 'numeric'
            });
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Morning greeting for ${date}`,
              body: '@claude good morning'
            });
            
            console.log(`Created issue #${issue.data.number}`);
            
            // Wait a bit to allow Claude to respond
            await new Promise(resolve => setTimeout(resolve, 30000)); // 30 seconds
            
            // Close the issue
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.data.number,
              state: 'closed'
            });
            
            console.log(`Closed issue #${issue.data.number}`);